### ISSUE TITLE
Enhancement for debug flags

### ISSUE THREAD

**Issue by impeeza** [mrdude2478/NRO-Forwarder#1]
Hello there Dude,  Thanks a lot for all your great work.

Reading the README.MD 

> 
> Advanced Hidden Feature (Fix Forwarders for certain firmware and AMS versions)
> 
> Clicking the Generate button and moving the mouse away from it, will select that button without making the forwader, you can then press either the "Z", "X", "C", "V" buttons on your keyboard to patch the debug flags in the main.npdm file.
> 
> Z = No Debug flags
> X = Allow Debug
> C = Use for firmware 18.0.x and below and < AMS 1.8.x
> V = Use for firmware 19.0.x and + AMS 1.8.x
> 

What do you think if you enable a submenu to configure this options which can be brough right-clicking the generate button?  After right clicking the generate button a new dialog with the options can pop up, having a generate and a cancel button, pressing cancel aborts the selection of flags and pressing generate from there, generate the forwarder with the flags selected on the dialog.

**Comment by mrdude2478** [comment]
Hi Impeeza, Once again I am banned from GBATemp :-). 

EDIT: New version released with patch box, it also shows the current state of the patch.
